[build]
  publish = "dist"
  command = "npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://your-render-backend-url.onrender.com"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://your-render-backend-url.onrender.com" 